name: ScoreMCPE
main: Ifera\ScoreHud\ScoreHud
api: 5.0.0
version: 6.6.1
authors: 
- Ifera
- NurAzliYT
description: Add fully customizable scoreboards to your server.

extensions:
  Core: '>=7.4'

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: true
    description: Allow players to use /scorehud command.
